name=HydroServerMQTTClient
version=
author=Sabin Panta 'Sabin <sabinpanta11@gmail.com>
maintainer=Sabin 'Panta <sabinpanta11@gmail.com>
sentence=
paragraph=
category=Communication
url=
architectures=
depends=ArduinoJson
